export interface Paciente {
  nombre: string;
  apellido: string;
  email: string;
  contrasenia: string;
  telefono: string;
  enfermedad: string; // Corresponds to 'diagnostico' in your form, 'enfermedad' in DTO
  edad: number;
  nombreResponsable: string;
  fechaNacimiento: string; 
  terapeuta_id: number;

  // Fields typically returned by the backend (PacienteOutputDTO)
  id?: number; // Optional, as it's generated by the backend upon creation
  usuario?: string; // Optional, as it's generated by the backend upon creation
}